# Generated by Django 3.2.4 on 2023-01-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='addharcard',
        ),
    ]
