# Generated by Django 3.2.4 on 2023-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0002_remove_accident_addharcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='image',
            field=models.ImageField(blank=True, upload_to='accident/images/'),
        ),
    ]
