# Generated by Django 3.2.4 on 2023-02-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0003_alter_accident_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='datecompleted',
        ),
        migrations.AlterField(
            model_name='accident',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accident',
            name='emergency_no1',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='accident',
            name='emergency_no2',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='accident',
            name='image',
            field=models.ImageField(upload_to='accident/images/'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='user_mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
