# Generated by Django 3.2.4 on 2023-02-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0005_auto_20230201_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_filler_name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=10)),
                ('accident_vehicle_number', models.CharField(max_length=20)),
                ('accident_image', models.ImageField(upload_to='accident/images/')),
                ('location_link', models.URLField(blank=True)),
            ],
        ),
    ]
